# Generated by Django 5.0.2 on 2024-02-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_de_publication',
            new_name='created_at',
        ),
    ]
